DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS program;
DROP TABLE IF EXISTS college;


-- Create the 'college' table
CREATE TABLE IF NOT EXISTS college (
    collegeCode VARCHAR(255) PRIMARY KEY,
    collegeName VARCHAR(255) NOT NULL
);

-- Create the 'program' table with both ON DELETE CASCADE and ON UPDATE CASCADE
CREATE TABLE IF NOT EXISTS program (
    programCode VARCHAR(255) PRIMARY KEY,
    programTitle VARCHAR(255),
    programCollege VARCHAR(255) NULL, -- must allow NULL
    FOREIGN KEY (programCollege) REFERENCES college(collegeCode)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

-- Create the 'student' table with foreign key to 'program' table
CREATE TABLE IF NOT EXISTS student (
    IDNumber VARCHAR(255) PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    CourseCode VARCHAR(255),
    Status VARCHAR(255) NOT NULL,
    Year VARCHAR(255) NOT NULL,
    Gender VARCHAR(255) NOT NULL,
    imageURL VARCHAR(255),
    FOREIGN KEY (CourseCode) REFERENCES program(programCode)
    ON DELETE SET NULL  -- Set CourseCode to NULL when a program is deleted
    ON UPDATE CASCADE   -- Update CourseCode when programCode is updated
);

-- Insert data into 'college' table
INSERT INTO college (collegeCode, collegeName) VALUES
('CCS', 'College of Computer Studies'),
('CASS', 'College of Arts and Social Sciences'),
('COE', 'College of Engineering'),
('CHS', 'College of Health and Sciences'),
('CSM', 'College of Science and Mathematics'),
('CEBA', 'College of Economics, Business and Accountancy');

-- Insert data into 'program' table
INSERT INTO program (programCode, programTitle, programCollege) VALUES
('BSCS', 'Bachelor of Science in Computer Science', 'CCS'),
('BSIT', 'Bachelor of Science in Information Technology', 'CCS'),
('BSCE', 'Bachelor of Science in Civil Engineering', 'COE'),
('BSEE', 'Bachelor of Science in Electrical Engineering', 'COE'),
('BSA', 'Bachelor of Science in Accountancy', 'CEBA'),
('BSBA', 'Bachelor of Science in Business Administration', 'CEBA'),
('BSBio', 'Bachelor of Science in Biology', 'CSM'),
('BSMath', 'Bachelor of Science in Mathematics', 'CSM'),
('BSPsych', 'Bachelor of Science in Psychology', 'CASS'),
('BSEd', 'Bachelor of Science in Education', 'CASS');

-- Insert data into 'student' table
INSERT INTO student (IDNumber, firstName, lastName, CourseCode, Status, Year, Gender, imageURL) VALUES
('2022-0001', 'Alice', 'Smith', 'BSCS', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0002', 'Bob', 'Brown', 'BSIT', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0003', 'Charlie', 'Davis', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0004', 'Diana', 'Evans', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0005', 'Eve', 'Johnson', 'BSA', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0006', 'Frank', 'Miller', 'BSBA', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0007', 'Grace', 'Wilson', 'BSBio', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0008', 'Hank', 'Taylor', 'BSMath', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0009', 'Ivy', 'Anderson', 'BSPsych', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0010', 'Jack', 'Thomas', 'BSEd', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0011', 'Kate', 'Harris', 'BSCS', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0012', 'Leo', 'Clark', 'BSIT', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0013', 'Mia', 'Lewis', 'BSCE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0014', 'Noah', 'Walker', 'BSEE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0015', 'Olivia', 'Hall', 'BSA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0016', 'Paul', 'Allen', 'BSBA', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0017', 'Quinn', 'Young', 'BSBio', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0018', 'Rose', 'King', 'BSMath', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0019', 'Sam', 'Scott', 'BSPsych', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0020', 'Tina', 'Adams', 'BSEd', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0021', 'Uma', 'Parker', 'BSCS', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0022', 'Victor', 'Collins', 'BSIT', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0023', 'Wendy', 'Mitchell', 'BSCE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0024', 'Xavier', 'Perez', 'BSEE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0025', 'Yvonne', 'Hughes', 'BSA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0026', 'Zach', 'Moore', 'BSCS', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0027', 'Anna', 'Taylor', 'BSIT', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0028', 'Ben', 'White', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0029', 'Carmen', 'Hernandez', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0030', 'David', 'Moore', 'BSA', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0031', 'Eva', 'Martinez', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0032', 'Felix', 'Gonzalez', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0033', 'Grace', 'Lopez', 'BSMath', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0034', 'Hugo', 'Perez', 'BSPsych', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0035', 'Isla', 'Roberts', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0036', 'James', 'Walker', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0037', 'Kara', 'Evans', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0038', 'Liam', 'Green', 'BSCE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0039', 'Maya', 'Adams', 'BSEE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0040', 'Nolan', 'Baker', 'BSA', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0041', 'Olga', 'Davis', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0042', 'Paul', 'Garcia', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0043', 'Quincy', 'Hall', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0044', 'Riley', 'King', 'BSPsych', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0045', 'Sophia', 'Lopez', 'BSEd', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0046', 'Thomas', 'Martinez', 'BSCS', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0047', 'Ursula', 'Gonzalez', 'BSIT', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0048', 'Vince', 'Baker', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0049', 'Willow', 'King', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0050', 'Xander', 'Green', 'BSA', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0051', 'Yara', 'Allen', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0052', 'Zane', 'Roberts', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0053', 'Amelia', 'Clark', 'BSMath', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0054', 'Brady', 'Davis', 'BSPsych', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0055', 'Chloe', 'Walker', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0056', 'Derek', 'Martinez', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0057', 'Eleanor', 'Lewis', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0058', 'Freddy', 'Hughes', 'BSCE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0059', 'Gina', 'Hall', 'BSEE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0060', 'Holly', 'Young', 'BSA', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0061', 'Iris', 'Garcia', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0062', 'Jack', 'Roberts', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0063', 'Kelsey', 'Wilson', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0064', 'Lara', 'Adams', 'BSPsych', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0065', 'Mason', 'Moore', 'BSEd', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0066', 'Nina', 'Baker', 'BSCS', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0067', 'Oscar', 'White', 'BSIT', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0068', 'Penny', 'Harris', 'BSCE', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0069', 'Quinn', 'Allen', 'BSEE', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0070', 'Riley', 'Green', 'BSA', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0071', 'Sophie', 'Collins', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0072', 'Tobias', 'Taylor', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0073', 'Uriah', 'Scott', 'BSMath', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0074', 'Vera', 'Brown', 'BSPsych', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0075', 'Wesley', 'Hughes', 'BSEd', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0076', 'Xena', 'King', 'BSCS', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0077', 'Yosef', 'Evans', 'BSIT', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0078', 'Zara', 'Parker', 'BSCE', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0079', 'Aaron', 'Martinez', 'BSEE', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0080', 'Beth', 'Collins', 'BSA', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0081', 'Carl', 'Mitchell', 'BSBA', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0082', 'Devin', 'Harris', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0083', 'Ella', 'Baker', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0084', 'Fiona', 'Clark', 'BSPsych', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0085', 'Gage', 'Gonzalez', 'BSEd', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0086', 'Holly', 'Lewis', 'BSCS', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0087', 'Ivy', 'Roberts', 'BSIT', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0088', 'James', 'Walker', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0089', 'Kimberly', 'Evans', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0090', 'Lance', 'Young', 'BSA', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0091', 'Maggie', 'Perez', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0092', 'Nate', 'King', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0093', 'Olivia', 'Davis', 'BSMath', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0094', 'Perry', 'Walker', 'BSPsych', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0095', 'Quincy', 'Roberts', 'BSEd', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0096', 'Randy', 'Moore', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0097', 'Samantha', 'Hughes', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0098', 'Toby', 'Green', 'BSCE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0099', 'Uma', 'Collins', 'BSEE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0100', 'Vera', 'Parker', 'BSA', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0101', 'Wendy', 'Scott', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0102', 'Xander', 'Parker', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0103', 'Yara', 'Moore', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0104', 'Zach', 'Mitchell', 'BSPsych', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0105', 'Aaron', 'King', 'BSEd', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0106', 'Bella', 'Walker', 'BSCS', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0107', 'Carl', 'Adams', 'BSIT', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0108', 'Diana', 'Parker', 'BSCE', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0109', 'Elena', 'Taylor', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0110', 'Frank', 'Hernandez', 'BSA', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0111', 'Grace', 'Baker', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0112', 'Hugh', 'Davis', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0113', 'Ivy', 'Moore', 'BSMath', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0114', 'John', 'Roberts', 'BSPsych', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0115', 'Kelsey', 'Parker', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0116', 'Leo', 'Martinez', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0117', 'Maya', 'King', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0118', 'Nina', 'Walker', 'BSCE', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0119', 'Oscar', 'Collins', 'BSEE', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0120', 'Paul', 'Hughes', 'BSA', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0121', 'Quinn', 'Mitchell', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0122', 'Rita', 'Moore', 'BSBio', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0123', 'Steve', 'Brown', 'BSMath', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0124', 'Tina', 'Baker', 'BSPsych', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0125', 'Ursula', 'Gonzalez', 'BSEd', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0126', 'Victor', 'Martinez', 'BSCS', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0127', 'Wendy', 'Roberts', 'BSIT', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0128', 'Xander', 'Collins', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0129', 'Yara', 'King', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0130', 'Zoe', 'Evans', 'BSA', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0131', 'Alex', 'Davis', 'BSBA', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0132', 'Beth', 'Taylor', 'BSBio', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0133', 'Carl', 'Lopez', 'BSMath', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0134', 'Diana', 'Roberts', 'BSPsych', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0135', 'Eve', 'Hughes', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0136', 'Finn', 'Walker', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0137', 'Grace', 'Gonzalez', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0138', 'Hugo', 'Collins', 'BSCE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0139', 'Isla', 'Baker', 'BSEE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0140', 'Jack', 'Adams', 'BSA', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0141', 'Kara', 'Roberts', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0142', 'Liam', 'Evans', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0143', 'Maggie', 'Mitchell', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0144', 'Nina', 'King', 'BSPsych', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0145', 'Oliver', 'Parker', 'BSEd', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0146', 'Penny', 'Green', 'BSCS', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0147', 'Quincy', 'Hernandez', 'BSIT', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0148', 'Riley', 'Lopez', 'BSCE', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0149', 'Sophie', 'Walker', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0150', 'Theo', 'Collins', 'BSA', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0151', 'Ursula', 'Davis', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0152', 'Victor', 'Taylor', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0153', 'Will', 'Adams', 'BSMath', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0154', 'Xena', 'Roberts', 'BSPsych', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0155', 'Yara', 'Collins', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0156', 'Zane', 'Parker', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0157', 'Alexis', 'Baker', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0158', 'Ben', 'Walker', 'BSCE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0159', 'Celia', 'Evans', 'BSEE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0160', 'Dylan', 'Hernandez', 'BSA', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0161', 'Ellie', 'King', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0162', 'Fred', 'Gonzalez', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0163', 'Greta', 'Lopez', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0164', 'Harry', 'Mitchell', 'BSPsych', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0165', 'Isla', 'Baker', 'BSEd', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0166', 'Jack', 'Taylor', 'BSCS', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0167', 'Kara', 'Walker', 'BSIT', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0168', 'Liam', 'Roberts', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0169', 'Maya', 'Hernandez', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0170', 'Nina', 'Collins', 'BSA', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0171', 'Oscar', 'King', 'BSBA', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0172', 'Paul', 'Parker', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0173', 'Quinn', 'Lopez', 'BSMath', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0174', 'Riley', 'Taylor', 'BSPsych', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0175', 'Sophia', 'Evans', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0176', 'Theo', 'Gonzalez', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0177', 'Ursula', 'Adams', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0178', 'Vera', 'Mitchell', 'BSCE', 'Enrolled', '4th Year', 'Female', NULL),
('2022-0179', 'Walter', 'Roberts', 'BSEE', 'Enrolled', '3rd Year', 'Male', NULL),
('2022-0180', 'Xander', 'Hernandez', 'BSA', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0181', 'Yara', 'Collins', 'BSBA', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0182', 'Zane', 'King', 'BSBio', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0183', 'Ava', 'Walker', 'BSMath', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0184', 'Blake', 'Gonzalez', 'BSPsych', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0185', 'Cara', 'Parker', 'BSEd', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0186', 'David', 'Lopez', 'BSCS', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0187', 'Ella', 'Roberts', 'BSIT', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0188', 'Finn', 'Collins', 'BSCE', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0189', 'Greta', 'Taylor', 'BSEE', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0190', 'Hugo', 'Evans', 'BSA', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0191', 'Ivy', 'Gonzalez', 'BSBA', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0192', 'Jack', 'Adams', 'BSBio', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0193', 'Kara', 'Walker', 'BSMath', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0194', 'Leo', 'Hernandez', 'BSPsych', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0195', 'Maggie', 'Parker', 'BSEd', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0196', 'Nathan', 'Collins', 'BSCS', 'Enrolled', '2nd Year', 'Male', NULL),
('2022-0197', 'Olivia', 'Mitchell', 'BSIT', 'Enrolled', '1st Year', 'Female', NULL),
('2022-0198', 'Peter', 'Roberts', 'BSCE', 'Enrolled', '4th Year', 'Male', NULL),
('2022-0199', 'Quinn', 'Evans', 'BSEE', 'Enrolled', '3rd Year', 'Female', NULL),
('2022-0200', 'Rita', 'Gonzalez', 'BSA', 'Enrolled', '2nd Year', 'Female', NULL),
('2022-0201', 'Steve', 'King', 'BSBA', 'Enrolled', '1st Year', 'Male', NULL),
('2022-0202', 'Tina', 'Walker', 'BSBio', 'Enrolled', '4th Year', 'Female', NULL);